# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=64)),
                ('remark', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_room', models.CharField(max_length=64)),
                ('motor_room_num', models.CharField(max_length=64)),
                ('Cabinet', models.CharField(max_length=64)),
                ('sn_no', models.CharField(max_length=64)),
                ('remark', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, null=True, verbose_name='主机名')),
                ('host_ip', models.CharField(max_length=20, unique=True)),
                ('ssh_port', models.CharField(default='22', max_length=4)),
                ('cpu', models.IntegerField(max_length=4, null=True)),
                ('mem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_vm', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
