# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171107_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostname',
            new_name='主机名',
        ),
    ]
