# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171107_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='主机名',
            new_name='hostname',
        ),
    ]
