# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171107_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='app',
            field=models.ManyToManyField(to='cmdb.app'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
