# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_host_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='OS_version',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
