# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_menu_service_line_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sl',
            field=models.ManyToManyField(to='cmdb.Service_Line'),
        ),
    ]
