# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20171108_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_line_name', models.CharField(max_length=50)),
            ],
        ),
    ]
