# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
