# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-08 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_is_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
